const $=s=>document.querySelector(s),api="/api/v1";let mode="login",token=localStorage.getItem("taskflow_token")||"",user=JSON.parse(localStorage.getItem("taskflow_user")||"null"),runs=[],selected=null;
const request=async(path,options={})=>{const response=await fetch(api+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data};
const toast=message=>{const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)};
const short=id=>id?`${id.slice(0,8)}…`:"—",date=value=>value?new Date(value).toLocaleString():"—";
const escape=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function setAuthMode(next){mode=next;const register=mode==="register";$("#name-field").classList.toggle("hidden",!register);$("#display-name").required=register;$("#auth-title").textContent=register?"Create an account":"Welcome back";$("#auth-copy").textContent=register?"Register a user and start scheduling tasks.":"Sign in to manage scheduled jobs.";$("#auth-submit").firstChild.textContent=register?"Register ":"Sign in ";$("#auth-switch").textContent=register?"Already registered? Sign in":"Need an account? Register";$("#auth-error").classList.add("hidden")}
$("#auth-switch").onclick=()=>setAuthMode(mode==="login"?"register":"login");
$("#auth-form").onsubmit=async event=>{event.preventDefault();const body={email:$("#email").value,password:$("#password").value};if(mode==="register")body.display_name=$("#display-name").value;try{const data=await request(`/auth/${mode}`,{method:"POST",body:JSON.stringify(body)});token=data.token;user=data.user;localStorage.setItem("taskflow_token",token);localStorage.setItem("taskflow_user",JSON.stringify(user));showApp()}catch(error){$("#auth-error").textContent=error.message;$("#auth-error").classList.remove("hidden")}};
function showApp(){$("#auth-view").classList.add("hidden");$("#app-view").classList.remove("hidden");$("#profile-name").textContent=user?.display_name||"User";$("#profile-email").textContent=user?.email||"";$("#avatar").textContent=(user?.display_name||"U").slice(0,1).toUpperCase();loadRuns()}
function logout(){token="";user=null;localStorage.removeItem("taskflow_token");localStorage.removeItem("taskflow_user");$("#app-view").classList.add("hidden");$("#auth-view").classList.remove("hidden")}
$("#logout").onclick=logout;
async function loadRuns(){try{const data=await request("/jobs?limit=100");runs=data.runs||[];renderRuns();$("#total-count").textContent=data.total;["pending","running","success"].forEach(status=>$(`#${status}-count`).textContent=runs.filter(run=>run.status===status).length)}catch(error){if(error.message.includes("unauth"))logout();else toast(error.message)}}
function renderRuns(){const query=$("#search").value.toLowerCase(),filtered=runs.filter(run=>run.job_id.toLowerCase().includes(query)||run.status.toLowerCase().includes(query));$("#runs").innerHTML=filtered.map(run=>`<tr data-id="${run.id}"><td><span class="job-id" title="${run.job_id}">${short(run.job_id)}</span></td><td><span class="status ${run.status}">${run.status}</span></td><td>${date(run.scheduled_at)}</td><td>${run.attempts}</td><td>${date(run.updated_at)}</td><td><button class="row-button">Inspect →</button></td></tr>`).join("");$("#empty").classList.toggle("hidden",filtered.length>0)}
$("#search").oninput=renderRuns;$("#refresh").onclick=loadRuns;$("#refresh-nav").onclick=loadRuns;$("#new-job").onclick=()=>{$("#modal").classList.remove("hidden");const next=new Date(Date.now()+60000);next.setMinutes(next.getMinutes()-next.getTimezoneOffset());$("#scheduled-at").value=next.toISOString().slice(0,16)};$("#recurring").onchange=event=>$("#interval-field").classList.toggle("hidden",!event.target.checked);
document.querySelectorAll('[data-close="modal"]').forEach(button=>button.onclick=()=>$("#modal").classList.add("hidden"));document.querySelectorAll('[data-close="drawer"]').forEach(button=>button.onclick=()=>$("#drawer").classList.remove("open"));
$("#job-form").onsubmit=async event=>{event.preventDefault();const body={description:$("#description").value,scheduled_at:new Date($("#scheduled-at").value).toISOString(),job_type:"generic_llm"};if($("#recurring").checked){body.schedule_type="recurring";body.recurring_interval_seconds=Number($("#interval").value)*60}else body.schedule_type="one_off";try{await request("/jobs",{method:"POST",body:JSON.stringify(body)});$("#modal").classList.add("hidden");event.target.reset();toast("Job created");loadRuns()}catch(error){$("#job-error").textContent=error.message;$("#job-error").classList.remove("hidden")}};
$("#runs").onclick=event=>{const row=event.target.closest("tr");if(row)openRun(runs.find(run=>run.id===row.dataset.id))};
async function openRun(run){selected=run;$("#drawer-title").textContent=`Job ${short(run.job_id)}`;const failure=run.error_message?`<div class="failure"><span>FAILURE REASON · ${escape(run.error_code||"execution_error")}</span><strong>${escape(run.error_message)}</strong></div>`:"";$("#run-detail").innerHTML=`<div class="detail-grid"><div><span>STATUS</span><strong class="status ${run.status}">${escape(run.status)}</strong></div><div><span>RETRIES</span><strong>${run.attempts}</strong></div><div><span>SCHEDULED</span><strong>${date(run.scheduled_at)}</strong></div><div><span>RUN ID</span><strong title="${escape(run.id)}">${short(run.id)}</strong></div></div>${failure}`;$("#drawer").classList.add("open");try{const [history,events]=await Promise.all([request(`/jobs/${run.job_id}/runs?limit=50`),request(`/runs/${run.id}/events`)]);$("#history").innerHTML=(history.runs||[]).map(item=>`<article><strong>${escape(item.status)} · ${item.attempts} retries</strong><small>${date(item.updated_at)}</small>${item.error_message?`<p>${escape(item.error_message)}</p>`:""}</article>`).join("")||"<small>No history found.</small>";$("#events").innerHTML=(events.events||[]).map(item=>{const payload=Object.keys(item.payload||{}).length?`<p>${escape(JSON.stringify(item.payload))}</p>`:"";return `<article><strong>${escape(item.event_type)} · ${escape(item.status)}</strong><small>${date(item.created_at)}</small>${payload}</article>`}).join("")||"<small>No events found.</small>"}catch(error){toast(error.message)}}
$("#cancel-job").onclick=async()=>{if(!selected)return;try{const result=await request(`/jobs/${selected.job_id}/cancel`,{method:"POST"});toast(`Cancelled ${result.cancelled_runs} pending run(s)`);$("#drawer").classList.remove("open");loadRuns()}catch(error){toast(error.message)}};$("#reload-detail").onclick=()=>selected&&openRun(selected);
if(token&&user)showApp();
