// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID              pgtype.UUID
	Kind            string
	Description     string
	IntervalSeconds int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JobRun struct {
	ID          pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	Status      string
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RunEvent struct {
	ID        pgtype.UUID
	JobRunID  pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
