// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobRuns = `-- name: CountJobRuns :one
SELECT COUNT(*) FROM job_runs WHERE tenant_id = $1
`

func (q *Queries) CountJobRuns(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobRuns, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findDueJobRuns = `-- name: FindDueJobRuns :many
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, created_at, updated_at
FROM job_runs
WHERE time_bucket <= $1
  AND status = 'pending'
  AND scheduled_at <= $2
ORDER BY scheduled_at
LIMIT $3
`

type FindDueJobRunsParams struct {
	TimeBucket int64
	DueBefore  pgtype.Timestamptz
	Lim        int32
}

type FindDueJobRunsRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	Status      string
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) FindDueJobRuns(ctx context.Context, arg FindDueJobRunsParams) ([]FindDueJobRunsRow, error) {
	rows, err := q.db.Query(ctx, findDueJobRuns, arg.TimeBucket, arg.DueBefore, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDueJobRunsRow{}
	for rows.Next() {
		var i FindDueJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.ScheduledAt,
			&i.TimeBucket,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, tenant_id, user_id, kind, description, interval_seconds, created_at, updated_at
FROM jobs WHERE id = $1
`

type GetJobByIDRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	UserID          pgtype.UUID
	Kind            string
	Description     string
	IntervalSeconds int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.Description,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobRunByID = `-- name: GetJobRunByID :one
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, created_at, updated_at
FROM job_runs WHERE id = $1
`

type GetJobRunByIDRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	Status      string
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetJobRunByID(ctx context.Context, id pgtype.UUID) (GetJobRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobRunByID, id)
	var i GetJobRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.ScheduledAt,
		&i.TimeBucket,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (id, tenant_id, user_id, kind, description, interval_seconds, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
`

type InsertJobParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	UserID          pgtype.UUID
	Kind            string
	Description     string
	IntervalSeconds int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.Description,
		arg.IntervalSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobRun = `-- name: InsertJobRun :exec
INSERT INTO job_runs (id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket,
                      attempts, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
`

type InsertJobRunParams struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	Status      string
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertJobRun(ctx context.Context, arg InsertJobRunParams) error {
	_, err := q.db.Exec(ctx, insertJobRun,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.Sequence,
		arg.Status,
		arg.ScheduledAt,
		arg.TimeBucket,
		arg.Attempts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobRunIfAbsent = `-- name: InsertJobRunIfAbsent :execrows
INSERT INTO job_runs (id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket,
                      attempts, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'pending',
        $5, $6, 0,
        $7, $8)
ON CONFLICT (job_id, sequence) DO NOTHING
`

type InsertJobRunIfAbsentParams struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertJobRunIfAbsent(ctx context.Context, arg InsertJobRunIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobRunIfAbsent,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.Sequence,
		arg.ScheduledAt,
		arg.TimeBucket,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (id, tenant_id, job_id, job_run_id, status, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6)
`

type InsertRunEventParams struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	JobID     pgtype.UUID
	JobRunID  pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.Exec(ctx, insertRunEvent,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.JobRunID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, created_at, updated_at
FROM job_runs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListJobRunsParams struct {
	TenantID   pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

type ListJobRunsRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	JobID       pgtype.UUID
	Sequence    int32
	Status      string
	ScheduledAt pgtype.Timestamptz
	TimeBucket  int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]ListJobRunsRow, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.TenantID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsRow{}
	for rows.Next() {
		var i ListJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.ScheduledAt,
			&i.TimeBucket,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalRecurringRuns = `-- name: ListTerminalRecurringRuns :many
SELECT r.id, r.tenant_id, r.job_id, r.sequence, r.scheduled_at, j.interval_seconds
FROM run_events e
JOIN job_runs r ON r.id = e.job_run_id
JOIN jobs     j ON j.id = r.job_id
WHERE e.status IN ('success','failed')
  AND j.kind = 'recurring'
  AND e.created_at >= $1
  AND NOT EXISTS (
        SELECT 1 FROM job_runs n WHERE n.job_id = r.job_id AND n.sequence = r.sequence + 1)
ORDER BY e.created_at
LIMIT $2
`

type ListTerminalRecurringRunsParams struct {
	Since pgtype.Timestamptz
	Lim   int32
}

type ListTerminalRecurringRunsRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	JobID           pgtype.UUID
	Sequence        int32
	ScheduledAt     pgtype.Timestamptz
	IntervalSeconds int64
}

func (q *Queries) ListTerminalRecurringRuns(ctx context.Context, arg ListTerminalRecurringRunsParams) ([]ListTerminalRecurringRunsRow, error) {
	rows, err := q.db.Query(ctx, listTerminalRecurringRuns, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTerminalRecurringRunsRow{}
	for rows.Next() {
		var i ListTerminalRecurringRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.ScheduledAt,
			&i.IntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobRunStatus = `-- name: UpdateJobRunStatus :execrows
UPDATE job_runs
SET status = $1, attempts = $2, updated_at = $3
WHERE id = $4
`

type UpdateJobRunStatusParams struct {
	Status    string
	Attempts  int32
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobRunStatus,
		arg.Status,
		arg.Attempts,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
