// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginIdempotency = `-- name: BeginIdempotency :execrows
INSERT INTO idempotency_records (
  idempotency_key, job_run_id, handler_name, status, created_at, updated_at
)
VALUES (
  $1, $2, $3,
  'in_progress', $4, $5
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type BeginIdempotencyParams struct {
	IdempotencyKey string
	JobRunID       pgtype.UUID
	HandlerName    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) BeginIdempotency(ctx context.Context, arg BeginIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginIdempotency,
		arg.IdempotencyKey,
		arg.JobRunID,
		arg.HandlerName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotency = `-- name: CompleteIdempotency :execrows
UPDATE idempotency_records
SET status = 'completed',
    response_hash = $1,
    updated_at = $2
WHERE idempotency_key = $3
`

type CompleteIdempotencyParams struct {
	ResponseHash   *string
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotency, arg.ResponseHash, arg.UpdatedAt, arg.IdempotencyKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveRecurringJobs = `-- name: CountActiveRecurringJobs :one
SELECT COUNT(*)
FROM jobs j
WHERE j.tenant_id = $1
  AND j.kind = 'recurring'
  AND EXISTS (
    SELECT 1
    FROM job_runs r
    WHERE r.job_id = j.id
      AND r.status NOT IN ('success', 'failed', 'cancelled')
  )
`

func (q *Queries) CountActiveRecurringJobs(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRecurringJobs, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobRuns = `-- name: CountJobRuns :one
SELECT COUNT(*) FROM job_runs WHERE tenant_id = $1
`

func (q *Queries) CountJobRuns(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobRuns, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobRunsByJob = `-- name: CountJobRunsByJob :one
SELECT COUNT(*) FROM job_runs
WHERE tenant_id = $1
  AND job_id = $2
`

type CountJobRunsByJobParams struct {
	TenantID pgtype.UUID
	JobID    pgtype.UUID
}

func (q *Queries) CountJobRunsByJob(ctx context.Context, arg CountJobRunsByJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobRunsByJob, arg.TenantID, arg.JobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsCreatedSince = `-- name: CountJobsCreatedSince :one
SELECT COUNT(*)
FROM jobs
WHERE tenant_id = $1
  AND created_at >= $2
`

type CountJobsCreatedSinceParams struct {
	TenantID pgtype.UUID
	Since    pgtype.Timestamptz
}

func (q *Queries) CountJobsCreatedSince(ctx context.Context, arg CountJobsCreatedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsCreatedSince, arg.TenantID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findChildJobs = `-- name: FindChildJobs :many
SELECT id, tenant_id, user_id, kind, description, interval_seconds, schedule_type,
       scheduled_at_utc, recurrence_rule, local_time, timezone_id, original_user_text,
       side_effecting, idempotency_scope, parent_job_id, trigger_on_parent_status, job_type,
       created_at, updated_at
FROM jobs
WHERE parent_job_id = $1
  AND trigger_on_parent_status = $2
ORDER BY created_at
`

type FindChildJobsParams struct {
	ParentJobID           pgtype.UUID
	TriggerOnParentStatus *string
}

type FindChildJobsRow struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	UserID                pgtype.UUID
	Kind                  string
	Description           string
	IntervalSeconds       int64
	ScheduleType          string
	ScheduledAtUtc        pgtype.Timestamptz
	RecurrenceRule        *string
	LocalTime             *string
	TimezoneID            string
	OriginalUserText      *string
	SideEffecting         bool
	IdempotencyScope      string
	ParentJobID           pgtype.UUID
	TriggerOnParentStatus *string
	JobType               string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) FindChildJobs(ctx context.Context, arg FindChildJobsParams) ([]FindChildJobsRow, error) {
	rows, err := q.db.Query(ctx, findChildJobs, arg.ParentJobID, arg.TriggerOnParentStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindChildJobsRow{}
	for rows.Next() {
		var i FindChildJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Kind,
			&i.Description,
			&i.IntervalSeconds,
			&i.ScheduleType,
			&i.ScheduledAtUtc,
			&i.RecurrenceRule,
			&i.LocalTime,
			&i.TimezoneID,
			&i.OriginalUserText,
			&i.SideEffecting,
			&i.IdempotencyScope,
			&i.ParentJobID,
			&i.TriggerOnParentStatus,
			&i.JobType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDueJobRuns = `-- name: FindDueJobRuns :many
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, idempotency_key,
       error_code, error_message, started_at, completed_at, failed_at, created_at, updated_at
FROM job_runs
WHERE time_bucket <= $1
  AND status = 'pending'
  AND scheduled_at <= $2
ORDER BY scheduled_at
LIMIT $3
`

type FindDueJobRunsParams struct {
	TimeBucket int64
	DueBefore  pgtype.Timestamptz
	Lim        int32
}

type FindDueJobRunsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	Status         string
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	Attempts       int32
	IdempotencyKey string
	ErrorCode      *string
	ErrorMessage   *string
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) FindDueJobRuns(ctx context.Context, arg FindDueJobRunsParams) ([]FindDueJobRunsRow, error) {
	rows, err := q.db.Query(ctx, findDueJobRuns, arg.TimeBucket, arg.DueBefore, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDueJobRunsRow{}
	for rows.Next() {
		var i FindDueJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.ScheduledAt,
			&i.TimeBucket,
			&i.Attempts,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT idempotency_key, handler_name, status, response_hash
FROM idempotency_records
WHERE idempotency_key = $1
`

type GetIdempotencyRow struct {
	IdempotencyKey string
	HandlerName    string
	Status         string
	ResponseHash   *string
}

func (q *Queries) GetIdempotency(ctx context.Context, idempotencyKey string) (GetIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotency, idempotencyKey)
	var i GetIdempotencyRow
	err := row.Scan(
		&i.IdempotencyKey,
		&i.HandlerName,
		&i.Status,
		&i.ResponseHash,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, tenant_id, user_id, kind, description, interval_seconds, schedule_type,
       scheduled_at_utc, recurrence_rule, local_time, timezone_id, original_user_text,
       side_effecting, idempotency_scope,
       parent_job_id, trigger_on_parent_status, job_type,
       created_at, updated_at
FROM jobs WHERE id = $1
`

type GetJobByIDRow struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	UserID                pgtype.UUID
	Kind                  string
	Description           string
	IntervalSeconds       int64
	ScheduleType          string
	ScheduledAtUtc        pgtype.Timestamptz
	RecurrenceRule        *string
	LocalTime             *string
	TimezoneID            string
	OriginalUserText      *string
	SideEffecting         bool
	IdempotencyScope      string
	ParentJobID           pgtype.UUID
	TriggerOnParentStatus *string
	JobType               string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.Description,
		&i.IntervalSeconds,
		&i.ScheduleType,
		&i.ScheduledAtUtc,
		&i.RecurrenceRule,
		&i.LocalTime,
		&i.TimezoneID,
		&i.OriginalUserText,
		&i.SideEffecting,
		&i.IdempotencyScope,
		&i.ParentJobID,
		&i.TriggerOnParentStatus,
		&i.JobType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobRunByID = `-- name: GetJobRunByID :one
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, idempotency_key,
       error_code, error_message, started_at, completed_at, failed_at, created_at, updated_at
FROM job_runs WHERE id = $1
`

type GetJobRunByIDRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	Status         string
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	Attempts       int32
	IdempotencyKey string
	ErrorCode      *string
	ErrorMessage   *string
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetJobRunByID(ctx context.Context, id pgtype.UUID) (GetJobRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobRunByID, id)
	var i GetJobRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.ScheduledAt,
		&i.TimeBucket,
		&i.Attempts,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantQuota = `-- name: GetTenantQuota :one
SELECT max_jobs_per_hour, max_active_recurring_jobs, max_concurrent_runs,
       max_daily_llm_cost_cents
FROM tenant_quotas
WHERE tenant_id = $1
`

type GetTenantQuotaRow struct {
	MaxJobsPerHour         int32
	MaxActiveRecurringJobs int32
	MaxConcurrentRuns      int32
	MaxDailyLlmCostCents   int32
}

func (q *Queries) GetTenantQuota(ctx context.Context, tenantID pgtype.UUID) (GetTenantQuotaRow, error) {
	row := q.db.QueryRow(ctx, getTenantQuota, tenantID)
	var i GetTenantQuotaRow
	err := row.Scan(
		&i.MaxJobsPerHour,
		&i.MaxActiveRecurringJobs,
		&i.MaxConcurrentRuns,
		&i.MaxDailyLlmCostCents,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (id, tenant_id, user_id, kind, description, interval_seconds, schedule_type,
                  scheduled_at_utc, recurrence_rule, local_time, timezone_id, original_user_text,
                  side_effecting, idempotency_scope,
                  parent_job_id, trigger_on_parent_status, job_type,
                  created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10,
        $11, $12, $13,
        $14, $15, $16,
        $17,
        $18, $19)
`

type InsertJobParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	UserID                pgtype.UUID
	Kind                  string
	Description           string
	IntervalSeconds       int64
	ScheduleType          string
	ScheduledAtUtc        pgtype.Timestamptz
	RecurrenceRule        *string
	LocalTime             *string
	TimezoneID            string
	OriginalUserText      *string
	SideEffecting         bool
	IdempotencyScope      string
	ParentJobID           pgtype.UUID
	TriggerOnParentStatus *string
	JobType               string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.Description,
		arg.IntervalSeconds,
		arg.ScheduleType,
		arg.ScheduledAtUtc,
		arg.RecurrenceRule,
		arg.LocalTime,
		arg.TimezoneID,
		arg.OriginalUserText,
		arg.SideEffecting,
		arg.IdempotencyScope,
		arg.ParentJobID,
		arg.TriggerOnParentStatus,
		arg.JobType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobRun = `-- name: InsertJobRun :exec
INSERT INTO job_runs (id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket,
                      attempts, idempotency_key, error_code, error_message, started_at, completed_at, failed_at,
                      created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10, $11,
        $12, $13, $14,
        $15, $16)
`

type InsertJobRunParams struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	Status         string
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	Attempts       int32
	IdempotencyKey string
	ErrorCode      *string
	ErrorMessage   *string
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertJobRun(ctx context.Context, arg InsertJobRunParams) error {
	_, err := q.db.Exec(ctx, insertJobRun,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.Sequence,
		arg.Status,
		arg.ScheduledAt,
		arg.TimeBucket,
		arg.Attempts,
		arg.IdempotencyKey,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobRunIfAbsent = `-- name: InsertJobRunIfAbsent :execrows
INSERT INTO job_runs (id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket,
                      attempts, idempotency_key, error_code, error_message, started_at, completed_at, failed_at,
                      created_at, updated_at)
VALUES ($1, $2, $3, $4, 'pending',
        $5, $6, 0, $7,
        NULL, NULL, NULL, NULL, NULL,
        $8, $9)
ON CONFLICT (job_id, sequence) DO NOTHING
`

type InsertJobRunIfAbsentParams struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertJobRunIfAbsent(ctx context.Context, arg InsertJobRunIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobRunIfAbsent,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.Sequence,
		arg.ScheduledAt,
		arg.TimeBucket,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (id, tenant_id, job_id, job_run_id, status, event_type, event_payload, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertRunEventParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	JobID        pgtype.UUID
	JobRunID     pgtype.UUID
	Status       string
	EventType    string
	EventPayload []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.Exec(ctx, insertRunEvent,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.JobRunID,
		arg.Status,
		arg.EventType,
		arg.EventPayload,
		arg.CreatedAt,
	)
	return err
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, idempotency_key,
       error_code, error_message, started_at, completed_at, failed_at, created_at, updated_at
FROM job_runs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListJobRunsParams struct {
	TenantID   pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

type ListJobRunsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	Status         string
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	Attempts       int32
	IdempotencyKey string
	ErrorCode      *string
	ErrorMessage   *string
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]ListJobRunsRow, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.TenantID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsRow{}
	for rows.Next() {
		var i ListJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.ScheduledAt,
			&i.TimeBucket,
			&i.Attempts,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRunsByJob = `-- name: ListJobRunsByJob :many
SELECT id, tenant_id, job_id, sequence, status, scheduled_at, time_bucket, attempts, idempotency_key,
       error_code, error_message, started_at, completed_at, failed_at, created_at, updated_at
FROM job_runs
WHERE tenant_id = $1
  AND job_id = $2
ORDER BY sequence
LIMIT $4 OFFSET $3
`

type ListJobRunsByJobParams struct {
	TenantID   pgtype.UUID
	JobID      pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

type ListJobRunsByJobRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	Status         string
	ScheduledAt    pgtype.Timestamptz
	TimeBucket     int64
	Attempts       int32
	IdempotencyKey string
	ErrorCode      *string
	ErrorMessage   *string
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListJobRunsByJob(ctx context.Context, arg ListJobRunsByJobParams) ([]ListJobRunsByJobRow, error) {
	rows, err := q.db.Query(ctx, listJobRunsByJob,
		arg.TenantID,
		arg.JobID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsByJobRow{}
	for rows.Next() {
		var i ListJobRunsByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.ScheduledAt,
			&i.TimeBucket,
			&i.Attempts,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEventsByRun = `-- name: ListRunEventsByRun :many
SELECT id, tenant_id, job_id, job_run_id, status, event_type, event_payload, created_at
FROM run_events
WHERE tenant_id = $1
  AND job_run_id = $2
ORDER BY created_at
`

type ListRunEventsByRunParams struct {
	TenantID pgtype.UUID
	JobRunID pgtype.UUID
}

type ListRunEventsByRunRow struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	JobID        pgtype.UUID
	JobRunID     pgtype.UUID
	Status       string
	EventType    string
	EventPayload []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRunEventsByRun(ctx context.Context, arg ListRunEventsByRunParams) ([]ListRunEventsByRunRow, error) {
	rows, err := q.db.Query(ctx, listRunEventsByRun, arg.TenantID, arg.JobRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunEventsByRunRow{}
	for rows.Next() {
		var i ListRunEventsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.JobRunID,
			&i.Status,
			&i.EventType,
			&i.EventPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalRecurringRuns = `-- name: ListTerminalRecurringRuns :many
SELECT r.id, r.tenant_id, r.job_id, r.sequence, r.scheduled_at,
       j.timezone_id, j.recurrence_rule, j.local_time
FROM run_events e
JOIN job_runs r ON r.id = e.job_run_id
JOIN jobs     j ON j.id = r.job_id
WHERE e.status IN ('success','failed')
  AND j.kind = 'recurring'
  AND e.created_at >= $1
  AND NOT EXISTS (
        SELECT 1 FROM job_runs n WHERE n.job_id = r.job_id AND n.sequence = r.sequence + 1)
ORDER BY e.created_at
LIMIT $2
`

type ListTerminalRecurringRunsParams struct {
	Since pgtype.Timestamptz
	Lim   int32
}

type ListTerminalRecurringRunsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	JobID          pgtype.UUID
	Sequence       int32
	ScheduledAt    pgtype.Timestamptz
	TimezoneID     string
	RecurrenceRule *string
	LocalTime      *string
}

func (q *Queries) ListTerminalRecurringRuns(ctx context.Context, arg ListTerminalRecurringRunsParams) ([]ListTerminalRecurringRunsRow, error) {
	rows, err := q.db.Query(ctx, listTerminalRecurringRuns, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTerminalRecurringRunsRow{}
	for rows.Next() {
		var i ListTerminalRecurringRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Sequence,
			&i.ScheduledAt,
			&i.TimezoneID,
			&i.RecurrenceRule,
			&i.LocalTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobRunStatus = `-- name: UpdateJobRunStatus :execrows
UPDATE job_runs
SET status = $1,
    attempts = $2,
    error_code = $3,
    error_message = $4,
    started_at = $5,
    completed_at = $6,
    failed_at = $7,
    updated_at = $8
WHERE id = $9
`

type UpdateJobRunStatusParams struct {
	Status       string
	Attempts     int32
	ErrorCode    *string
	ErrorMessage *string
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	FailedAt     pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobRunStatus,
		arg.Status,
		arg.Attempts,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
