// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	shared "github.com/linkc0829/go-chatgpt-tasks/internal/shared"
	task "github.com/linkc0829/go-chatgpt-tasks/internal/task"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AppendEvent mocks base method.
func (m *MockRepo) AppendEvent(ctx context.Context, e *task.RunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockRepoMockRecorder) AppendEvent(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockRepo)(nil).AppendEvent), ctx, e)
}

// FindDueRuns mocks base method.
func (m *MockRepo) FindDueRuns(ctx context.Context, bucket int64, before time.Time, limit int32) ([]*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDueRuns", ctx, bucket, before, limit)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDueRuns indicates an expected call of FindDueRuns.
func (mr *MockRepoMockRecorder) FindDueRuns(ctx, bucket, before, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDueRuns", reflect.TypeOf((*MockRepo)(nil).FindDueRuns), ctx, bucket, before, limit)
}

// FindJob mocks base method.
func (m *MockRepo) FindJob(ctx context.Context, id shared.JobID) (*task.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJob", ctx, id)
	ret0, _ := ret[0].(*task.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJob indicates an expected call of FindJob.
func (mr *MockRepoMockRecorder) FindJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJob", reflect.TypeOf((*MockRepo)(nil).FindJob), ctx, id)
}

// FindRunByID mocks base method.
func (m *MockRepo) FindRunByID(ctx context.Context, id shared.JobRunID) (*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRunByID", ctx, id)
	ret0, _ := ret[0].(*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRunByID indicates an expected call of FindRunByID.
func (mr *MockRepoMockRecorder) FindRunByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRunByID", reflect.TypeOf((*MockRepo)(nil).FindRunByID), ctx, id)
}

// FindTerminalRecurringRuns mocks base method.
func (m *MockRepo) FindTerminalRecurringRuns(ctx context.Context, since time.Time, limit int32) ([]task.NextRunSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTerminalRecurringRuns", ctx, since, limit)
	ret0, _ := ret[0].([]task.NextRunSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTerminalRecurringRuns indicates an expected call of FindTerminalRecurringRuns.
func (mr *MockRepoMockRecorder) FindTerminalRecurringRuns(ctx, since, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTerminalRecurringRuns", reflect.TypeOf((*MockRepo)(nil).FindTerminalRecurringRuns), ctx, since, limit)
}

// InsertRunIfAbsent mocks base method.
func (m *MockRepo) InsertRunIfAbsent(ctx context.Context, r *task.JobRun) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRunIfAbsent", ctx, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRunIfAbsent indicates an expected call of InsertRunIfAbsent.
func (mr *MockRepoMockRecorder) InsertRunIfAbsent(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRunIfAbsent", reflect.TypeOf((*MockRepo)(nil).InsertRunIfAbsent), ctx, r)
}

// ListEvents mocks base method.
func (m *MockRepo) ListEvents(ctx context.Context, tenantID shared.TenantID, runID shared.JobRunID) ([]*task.RunEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, tenantID, runID)
	ret0, _ := ret[0].([]*task.RunEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockRepoMockRecorder) ListEvents(ctx, tenantID, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockRepo)(nil).ListEvents), ctx, tenantID, runID)
}

// ListRuns mocks base method.
func (m *MockRepo) ListRuns(ctx context.Context, tenantID shared.TenantID, p shared.Pagination) ([]*task.JobRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRuns", ctx, tenantID, p)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRuns indicates an expected call of ListRuns.
func (mr *MockRepoMockRecorder) ListRuns(ctx, tenantID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRuns", reflect.TypeOf((*MockRepo)(nil).ListRuns), ctx, tenantID, p)
}

// ListRunsByJob mocks base method.
func (m *MockRepo) ListRunsByJob(ctx context.Context, tenantID shared.TenantID, jobID shared.JobID, p shared.Pagination) ([]*task.JobRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunsByJob", ctx, tenantID, jobID, p)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRunsByJob indicates an expected call of ListRunsByJob.
func (mr *MockRepoMockRecorder) ListRunsByJob(ctx, tenantID, jobID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunsByJob", reflect.TypeOf((*MockRepo)(nil).ListRunsByJob), ctx, tenantID, jobID, p)
}

// SaveJob mocks base method.
func (m *MockRepo) SaveJob(ctx context.Context, j *task.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJob", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJob indicates an expected call of SaveJob.
func (mr *MockRepoMockRecorder) SaveJob(ctx, j interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJob", reflect.TypeOf((*MockRepo)(nil).SaveJob), ctx, j)
}

// SaveRun mocks base method.
func (m *MockRepo) SaveRun(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRun", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRun indicates an expected call of SaveRun.
func (mr *MockRepoMockRecorder) SaveRun(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRun", reflect.TypeOf((*MockRepo)(nil).SaveRun), ctx, r)
}

// UpdateRunStatus mocks base method.
func (m *MockRepo) UpdateRunStatus(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunStatus", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunStatus indicates an expected call of UpdateRunStatus.
func (mr *MockRepoMockRecorder) UpdateRunStatus(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunStatus", reflect.TypeOf((*MockRepo)(nil).UpdateRunStatus), ctx, r)
}

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockQueue) Ack(ctx context.Context, streamID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockQueueMockRecorder) Ack(ctx, streamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockQueue)(nil).Ack), ctx, streamID)
}

// DeadLetter mocks base method.
func (m_2 *MockQueue) DeadLetter(ctx context.Context, m task.JobRunMsg) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "DeadLetter", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeadLetter indicates an expected call of DeadLetter.
func (mr *MockQueueMockRecorder) DeadLetter(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadLetter", reflect.TypeOf((*MockQueue)(nil).DeadLetter), ctx, m)
}

// Enqueue mocks base method.
func (m_2 *MockQueue) Enqueue(ctx context.Context, m task.JobRunMsg) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Enqueue", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueMockRecorder) Enqueue(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueue)(nil).Enqueue), ctx, m)
}

// EnsureGroup mocks base method.
func (m *MockQueue) EnsureGroup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGroup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGroup indicates an expected call of EnsureGroup.
func (mr *MockQueueMockRecorder) EnsureGroup(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGroup", reflect.TypeOf((*MockQueue)(nil).EnsureGroup), ctx)
}

// Read mocks base method.
func (m *MockQueue) Read(ctx context.Context, consumer string, count int64, block time.Duration) ([]task.QueuedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, consumer, count, block)
	ret0, _ := ret[0].([]task.QueuedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockQueueMockRecorder) Read(ctx, consumer, count, block interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockQueue)(nil).Read), ctx, consumer, count, block)
}

// Reclaim mocks base method.
func (m *MockQueue) Reclaim(ctx context.Context, consumer string, minIdle time.Duration, count int64) ([]task.QueuedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reclaim", ctx, consumer, minIdle, count)
	ret0, _ := ret[0].([]task.QueuedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reclaim indicates an expected call of Reclaim.
func (mr *MockQueueMockRecorder) Reclaim(ctx, consumer, minIdle, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reclaim", reflect.TypeOf((*MockQueue)(nil).Reclaim), ctx, consumer, minIdle, count)
}

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, r)
}

// MockTenantResolver is a mock of TenantResolver interface.
type MockTenantResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTenantResolverMockRecorder
}

// MockTenantResolverMockRecorder is the mock recorder for MockTenantResolver.
type MockTenantResolverMockRecorder struct {
	mock *MockTenantResolver
}

// NewMockTenantResolver creates a new mock instance.
func NewMockTenantResolver(ctrl *gomock.Controller) *MockTenantResolver {
	mock := &MockTenantResolver{ctrl: ctrl}
	mock.recorder = &MockTenantResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantResolver) EXPECT() *MockTenantResolverMockRecorder {
	return m.recorder
}

// ResolveTenant mocks base method.
func (m *MockTenantResolver) ResolveTenant(ctx context.Context, userID shared.UserID) (shared.TenantID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTenant", ctx, userID)
	ret0, _ := ret[0].(shared.TenantID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTenant indicates an expected call of ResolveTenant.
func (mr *MockTenantResolverMockRecorder) ResolveTenant(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTenant", reflect.TypeOf((*MockTenantResolver)(nil).ResolveTenant), ctx, userID)
}
