// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	shared "github.com/linkc0829/go-backend-template/internal/shared"
	task "github.com/linkc0829/go-backend-template/internal/task"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AppendEvent mocks base method.
func (m *MockRepo) AppendEvent(ctx context.Context, e *task.RunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockRepoMockRecorder) AppendEvent(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockRepo)(nil).AppendEvent), ctx, e)
}

// FindDueRuns mocks base method.
func (m *MockRepo) FindDueRuns(ctx context.Context, bucket int64, before time.Time, limit int32) ([]*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDueRuns", ctx, bucket, before, limit)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDueRuns indicates an expected call of FindDueRuns.
func (mr *MockRepoMockRecorder) FindDueRuns(ctx, bucket, before, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDueRuns", reflect.TypeOf((*MockRepo)(nil).FindDueRuns), ctx, bucket, before, limit)
}

// FindJob mocks base method.
func (m *MockRepo) FindJob(ctx context.Context, id shared.JobID) (*task.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJob", ctx, id)
	ret0, _ := ret[0].(*task.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJob indicates an expected call of FindJob.
func (mr *MockRepoMockRecorder) FindJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJob", reflect.TypeOf((*MockRepo)(nil).FindJob), ctx, id)
}

// FindRunByID mocks base method.
func (m *MockRepo) FindRunByID(ctx context.Context, id shared.JobRunID) (*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRunByID", ctx, id)
	ret0, _ := ret[0].(*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRunByID indicates an expected call of FindRunByID.
func (mr *MockRepoMockRecorder) FindRunByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRunByID", reflect.TypeOf((*MockRepo)(nil).FindRunByID), ctx, id)
}

// FindTerminalRecurringRuns mocks base method.
func (m *MockRepo) FindTerminalRecurringRuns(ctx context.Context, since time.Time, limit int32) ([]task.NextRunSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTerminalRecurringRuns", ctx, since, limit)
	ret0, _ := ret[0].([]task.NextRunSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTerminalRecurringRuns indicates an expected call of FindTerminalRecurringRuns.
func (mr *MockRepoMockRecorder) FindTerminalRecurringRuns(ctx, since, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTerminalRecurringRuns", reflect.TypeOf((*MockRepo)(nil).FindTerminalRecurringRuns), ctx, since, limit)
}

// InsertRunIfAbsent mocks base method.
func (m *MockRepo) InsertRunIfAbsent(ctx context.Context, r *task.JobRun) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRunIfAbsent", ctx, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRunIfAbsent indicates an expected call of InsertRunIfAbsent.
func (mr *MockRepoMockRecorder) InsertRunIfAbsent(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRunIfAbsent", reflect.TypeOf((*MockRepo)(nil).InsertRunIfAbsent), ctx, r)
}

// ListRuns mocks base method.
func (m *MockRepo) ListRuns(ctx context.Context, p shared.Pagination) ([]*task.JobRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRuns", ctx, p)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRuns indicates an expected call of ListRuns.
func (mr *MockRepoMockRecorder) ListRuns(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRuns", reflect.TypeOf((*MockRepo)(nil).ListRuns), ctx, p)
}

// SaveJob mocks base method.
func (m *MockRepo) SaveJob(ctx context.Context, j *task.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJob", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJob indicates an expected call of SaveJob.
func (mr *MockRepoMockRecorder) SaveJob(ctx, j interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJob", reflect.TypeOf((*MockRepo)(nil).SaveJob), ctx, j)
}

// SaveRun mocks base method.
func (m *MockRepo) SaveRun(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRun", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRun indicates an expected call of SaveRun.
func (mr *MockRepoMockRecorder) SaveRun(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRun", reflect.TypeOf((*MockRepo)(nil).SaveRun), ctx, r)
}

// UpdateRunStatus mocks base method.
func (m *MockRepo) UpdateRunStatus(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunStatus", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunStatus indicates an expected call of UpdateRunStatus.
func (mr *MockRepoMockRecorder) UpdateRunStatus(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunStatus", reflect.TypeOf((*MockRepo)(nil).UpdateRunStatus), ctx, r)
}

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m_2 *MockQueue) Enqueue(ctx context.Context, m task.JobRunMsg) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Enqueue", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueMockRecorder) Enqueue(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueue)(nil).Enqueue), ctx, m)
}
