// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	shared "github.com/linkc0829/go-chatgpt-tasks/internal/shared"
	task "github.com/linkc0829/go-chatgpt-tasks/internal/task"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AppendEvent mocks base method.
func (m *MockRepo) AppendEvent(ctx context.Context, e *task.RunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockRepoMockRecorder) AppendEvent(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockRepo)(nil).AppendEvent), ctx, e)
}

// CancelPendingRunsByJob mocks base method.
func (m *MockRepo) CancelPendingRunsByJob(ctx context.Context, tenantID shared.TenantID, jobID shared.JobID) ([]*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPendingRunsByJob", ctx, tenantID, jobID)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPendingRunsByJob indicates an expected call of CancelPendingRunsByJob.
func (mr *MockRepoMockRecorder) CancelPendingRunsByJob(ctx, tenantID, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPendingRunsByJob", reflect.TypeOf((*MockRepo)(nil).CancelPendingRunsByJob), ctx, tenantID, jobID)
}

// CreateJobWithRun mocks base method.
func (m *MockRepo) CreateJobWithRun(ctx context.Context, j *task.Job, run *task.JobRun, events []*task.RunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobWithRun", ctx, j, run, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJobWithRun indicates an expected call of CreateJobWithRun.
func (mr *MockRepoMockRecorder) CreateJobWithRun(ctx, j, run, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobWithRun", reflect.TypeOf((*MockRepo)(nil).CreateJobWithRun), ctx, j, run, events)
}

// FindChildren mocks base method.
func (m *MockRepo) FindChildren(ctx context.Context, jobID shared.JobID, status task.Status) ([]*task.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChildren", ctx, jobID, status)
	ret0, _ := ret[0].([]*task.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChildren indicates an expected call of FindChildren.
func (mr *MockRepoMockRecorder) FindChildren(ctx, jobID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChildren", reflect.TypeOf((*MockRepo)(nil).FindChildren), ctx, jobID, status)
}

// FindDueRuns mocks base method.
func (m *MockRepo) FindDueRuns(ctx context.Context, bucket int64, before time.Time, limit int32) ([]*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDueRuns", ctx, bucket, before, limit)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDueRuns indicates an expected call of FindDueRuns.
func (mr *MockRepoMockRecorder) FindDueRuns(ctx, bucket, before, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDueRuns", reflect.TypeOf((*MockRepo)(nil).FindDueRuns), ctx, bucket, before, limit)
}

// FindJob mocks base method.
func (m *MockRepo) FindJob(ctx context.Context, id shared.JobID) (*task.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJob", ctx, id)
	ret0, _ := ret[0].(*task.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJob indicates an expected call of FindJob.
func (mr *MockRepoMockRecorder) FindJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJob", reflect.TypeOf((*MockRepo)(nil).FindJob), ctx, id)
}

// FindRunByID mocks base method.
func (m *MockRepo) FindRunByID(ctx context.Context, id shared.JobRunID) (*task.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRunByID", ctx, id)
	ret0, _ := ret[0].(*task.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRunByID indicates an expected call of FindRunByID.
func (mr *MockRepoMockRecorder) FindRunByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRunByID", reflect.TypeOf((*MockRepo)(nil).FindRunByID), ctx, id)
}

// FindTerminalRecurringRuns mocks base method.
func (m *MockRepo) FindTerminalRecurringRuns(ctx context.Context, since time.Time, limit int32) ([]task.NextRunSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTerminalRecurringRuns", ctx, since, limit)
	ret0, _ := ret[0].([]task.NextRunSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTerminalRecurringRuns indicates an expected call of FindTerminalRecurringRuns.
func (mr *MockRepoMockRecorder) FindTerminalRecurringRuns(ctx, since, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTerminalRecurringRuns", reflect.TypeOf((*MockRepo)(nil).FindTerminalRecurringRuns), ctx, since, limit)
}

// InsertRunIfAbsent mocks base method.
func (m *MockRepo) InsertRunIfAbsent(ctx context.Context, r *task.JobRun) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRunIfAbsent", ctx, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRunIfAbsent indicates an expected call of InsertRunIfAbsent.
func (mr *MockRepoMockRecorder) InsertRunIfAbsent(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRunIfAbsent", reflect.TypeOf((*MockRepo)(nil).InsertRunIfAbsent), ctx, r)
}

// ListEvents mocks base method.
func (m *MockRepo) ListEvents(ctx context.Context, tenantID shared.TenantID, runID shared.JobRunID) ([]*task.RunEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, tenantID, runID)
	ret0, _ := ret[0].([]*task.RunEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockRepoMockRecorder) ListEvents(ctx, tenantID, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockRepo)(nil).ListEvents), ctx, tenantID, runID)
}

// ListRuns mocks base method.
func (m *MockRepo) ListRuns(ctx context.Context, tenantID shared.TenantID, p shared.Pagination) ([]*task.JobRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRuns", ctx, tenantID, p)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRuns indicates an expected call of ListRuns.
func (mr *MockRepoMockRecorder) ListRuns(ctx, tenantID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRuns", reflect.TypeOf((*MockRepo)(nil).ListRuns), ctx, tenantID, p)
}

// ListRunsByJob mocks base method.
func (m *MockRepo) ListRunsByJob(ctx context.Context, tenantID shared.TenantID, jobID shared.JobID, p shared.Pagination) ([]*task.JobRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunsByJob", ctx, tenantID, jobID, p)
	ret0, _ := ret[0].([]*task.JobRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRunsByJob indicates an expected call of ListRunsByJob.
func (mr *MockRepoMockRecorder) ListRunsByJob(ctx, tenantID, jobID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunsByJob", reflect.TypeOf((*MockRepo)(nil).ListRunsByJob), ctx, tenantID, jobID, p)
}

// PersistRunTransition mocks base method.
func (m *MockRepo) PersistRunTransition(ctx context.Context, r *task.JobRun, event *task.RunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistRunTransition", ctx, r, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistRunTransition indicates an expected call of PersistRunTransition.
func (mr *MockRepoMockRecorder) PersistRunTransition(ctx, r, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistRunTransition", reflect.TypeOf((*MockRepo)(nil).PersistRunTransition), ctx, r, event)
}

// SaveJob mocks base method.
func (m *MockRepo) SaveJob(ctx context.Context, j *task.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJob", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJob indicates an expected call of SaveJob.
func (mr *MockRepoMockRecorder) SaveJob(ctx, j interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJob", reflect.TypeOf((*MockRepo)(nil).SaveJob), ctx, j)
}

// SaveRun mocks base method.
func (m *MockRepo) SaveRun(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRun", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRun indicates an expected call of SaveRun.
func (mr *MockRepoMockRecorder) SaveRun(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRun", reflect.TypeOf((*MockRepo)(nil).SaveRun), ctx, r)
}

// TryMarkRunRunning mocks base method.
func (m *MockRepo) TryMarkRunRunning(ctx context.Context, r *task.JobRun, event *task.RunEvent, limit int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryMarkRunRunning", ctx, r, event, limit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryMarkRunRunning indicates an expected call of TryMarkRunRunning.
func (mr *MockRepoMockRecorder) TryMarkRunRunning(ctx, r, event, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryMarkRunRunning", reflect.TypeOf((*MockRepo)(nil).TryMarkRunRunning), ctx, r, event, limit)
}

// UpdateRunStatus mocks base method.
func (m *MockRepo) UpdateRunStatus(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunStatus", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunStatus indicates an expected call of UpdateRunStatus.
func (mr *MockRepoMockRecorder) UpdateRunStatus(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunStatus", reflect.TypeOf((*MockRepo)(nil).UpdateRunStatus), ctx, r)
}

// MockQuotaRepo is a mock of QuotaRepo interface.
type MockQuotaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRepoMockRecorder
}

// MockQuotaRepoMockRecorder is the mock recorder for MockQuotaRepo.
type MockQuotaRepoMockRecorder struct {
	mock *MockQuotaRepo
}

// NewMockQuotaRepo creates a new mock instance.
func NewMockQuotaRepo(ctrl *gomock.Controller) *MockQuotaRepo {
	mock := &MockQuotaRepo{ctrl: ctrl}
	mock.recorder = &MockQuotaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRepo) EXPECT() *MockQuotaRepoMockRecorder {
	return m.recorder
}

// AdjustDailyCost mocks base method.
func (m *MockQuotaRepo) AdjustDailyCost(ctx context.Context, tenantID shared.TenantID, deltaCents int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustDailyCost", ctx, tenantID, deltaCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdjustDailyCost indicates an expected call of AdjustDailyCost.
func (mr *MockQuotaRepoMockRecorder) AdjustDailyCost(ctx, tenantID, deltaCents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustDailyCost", reflect.TypeOf((*MockQuotaRepo)(nil).AdjustDailyCost), ctx, tenantID, deltaCents)
}

// CountActiveRecurring mocks base method.
func (m *MockQuotaRepo) CountActiveRecurring(ctx context.Context, tenantID shared.TenantID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveRecurring", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveRecurring indicates an expected call of CountActiveRecurring.
func (mr *MockQuotaRepoMockRecorder) CountActiveRecurring(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveRecurring", reflect.TypeOf((*MockQuotaRepo)(nil).CountActiveRecurring), ctx, tenantID)
}

// CountActiveRuns mocks base method.
func (m *MockQuotaRepo) CountActiveRuns(ctx context.Context, tenantID shared.TenantID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveRuns", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveRuns indicates an expected call of CountActiveRuns.
func (mr *MockQuotaRepoMockRecorder) CountActiveRuns(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveRuns", reflect.TypeOf((*MockQuotaRepo)(nil).CountActiveRuns), ctx, tenantID)
}

// CountJobsSince mocks base method.
func (m *MockQuotaRepo) CountJobsSince(ctx context.Context, tenantID shared.TenantID, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountJobsSince", ctx, tenantID, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountJobsSince indicates an expected call of CountJobsSince.
func (mr *MockQuotaRepoMockRecorder) CountJobsSince(ctx, tenantID, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountJobsSince", reflect.TypeOf((*MockQuotaRepo)(nil).CountJobsSince), ctx, tenantID, since)
}

// Get mocks base method.
func (m *MockQuotaRepo) Get(ctx context.Context, tenantID shared.TenantID) (task.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID)
	ret0, _ := ret[0].(task.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuotaRepoMockRecorder) Get(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuotaRepo)(nil).Get), ctx, tenantID)
}

// ReserveDailyCost mocks base method.
func (m *MockQuotaRepo) ReserveDailyCost(ctx context.Context, tenantID shared.TenantID, costCents, limitCents int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveDailyCost", ctx, tenantID, costCents, limitCents)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveDailyCost indicates an expected call of ReserveDailyCost.
func (mr *MockQuotaRepoMockRecorder) ReserveDailyCost(ctx, tenantID, costCents, limitCents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveDailyCost", reflect.TypeOf((*MockQuotaRepo)(nil).ReserveDailyCost), ctx, tenantID, costCents, limitCents)
}

// MockQuotaRejectionRecorder is a mock of QuotaRejectionRecorder interface.
type MockQuotaRejectionRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRejectionRecorderMockRecorder
}

// MockQuotaRejectionRecorderMockRecorder is the mock recorder for MockQuotaRejectionRecorder.
type MockQuotaRejectionRecorderMockRecorder struct {
	mock *MockQuotaRejectionRecorder
}

// NewMockQuotaRejectionRecorder creates a new mock instance.
func NewMockQuotaRejectionRecorder(ctrl *gomock.Controller) *MockQuotaRejectionRecorder {
	mock := &MockQuotaRejectionRecorder{ctrl: ctrl}
	mock.recorder = &MockQuotaRejectionRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRejectionRecorder) EXPECT() *MockQuotaRejectionRecorderMockRecorder {
	return m.recorder
}

// RecordQuotaRejection mocks base method.
func (m *MockQuotaRejectionRecorder) RecordQuotaRejection(tenantID shared.TenantID, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordQuotaRejection", tenantID, reason)
}

// RecordQuotaRejection indicates an expected call of RecordQuotaRejection.
func (mr *MockQuotaRejectionRecorderMockRecorder) RecordQuotaRejection(tenantID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordQuotaRejection", reflect.TypeOf((*MockQuotaRejectionRecorder)(nil).RecordQuotaRejection), tenantID, reason)
}

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockIdempotencyStore) Begin(ctx context.Context, key, handler string, runID shared.JobRunID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, key, handler, runID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockIdempotencyStoreMockRecorder) Begin(ctx, key, handler, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockIdempotencyStore)(nil).Begin), ctx, key, handler, runID)
}

// Complete mocks base method.
func (m *MockIdempotencyStore) Complete(ctx context.Context, key, responseHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, key, responseHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockIdempotencyStoreMockRecorder) Complete(ctx, key, responseHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockIdempotencyStore)(nil).Complete), ctx, key, responseHash)
}

// Lookup mocks base method.
func (m *MockIdempotencyStore) Lookup(ctx context.Context, key string) (task.IdempotencyRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, key)
	ret0, _ := ret[0].(task.IdempotencyRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Lookup indicates an expected call of Lookup.
func (mr *MockIdempotencyStoreMockRecorder) Lookup(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockIdempotencyStore)(nil).Lookup), ctx, key)
}

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockQueue) Ack(ctx context.Context, streamID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockQueueMockRecorder) Ack(ctx, streamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockQueue)(nil).Ack), ctx, streamID)
}

// DeadLetter mocks base method.
func (m_2 *MockQueue) DeadLetter(ctx context.Context, m task.JobRunMsg) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "DeadLetter", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeadLetter indicates an expected call of DeadLetter.
func (mr *MockQueueMockRecorder) DeadLetter(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadLetter", reflect.TypeOf((*MockQueue)(nil).DeadLetter), ctx, m)
}

// Enqueue mocks base method.
func (m_2 *MockQueue) Enqueue(ctx context.Context, m task.JobRunMsg) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Enqueue", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueMockRecorder) Enqueue(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueue)(nil).Enqueue), ctx, m)
}

// EnsureGroup mocks base method.
func (m *MockQueue) EnsureGroup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGroup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGroup indicates an expected call of EnsureGroup.
func (mr *MockQueueMockRecorder) EnsureGroup(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGroup", reflect.TypeOf((*MockQueue)(nil).EnsureGroup), ctx)
}

// Read mocks base method.
func (m *MockQueue) Read(ctx context.Context, consumer string, count int64, block time.Duration) ([]task.QueuedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, consumer, count, block)
	ret0, _ := ret[0].([]task.QueuedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockQueueMockRecorder) Read(ctx, consumer, count, block interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockQueue)(nil).Read), ctx, consumer, count, block)
}

// Reclaim mocks base method.
func (m *MockQueue) Reclaim(ctx context.Context, consumer string, minIdle time.Duration, count int64) ([]task.QueuedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reclaim", ctx, consumer, minIdle, count)
	ret0, _ := ret[0].([]task.QueuedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reclaim indicates an expected call of Reclaim.
func (mr *MockQueueMockRecorder) Reclaim(ctx, consumer, minIdle, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reclaim", reflect.TypeOf((*MockQueue)(nil).Reclaim), ctx, consumer, minIdle, count)
}

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, r *task.JobRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, r)
}

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockLLMClient) Complete(ctx context.Context, req task.LLMRequest) (task.LLMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, req)
	ret0, _ := ret[0].(task.LLMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockLLMClientMockRecorder) Complete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockLLMClient)(nil).Complete), ctx, req)
}

// MockTenantResolver is a mock of TenantResolver interface.
type MockTenantResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTenantResolverMockRecorder
}

// MockTenantResolverMockRecorder is the mock recorder for MockTenantResolver.
type MockTenantResolverMockRecorder struct {
	mock *MockTenantResolver
}

// NewMockTenantResolver creates a new mock instance.
func NewMockTenantResolver(ctrl *gomock.Controller) *MockTenantResolver {
	mock := &MockTenantResolver{ctrl: ctrl}
	mock.recorder = &MockTenantResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantResolver) EXPECT() *MockTenantResolverMockRecorder {
	return m.recorder
}

// ResolveTenant mocks base method.
func (m *MockTenantResolver) ResolveTenant(ctx context.Context, userID shared.UserID) (shared.TenantID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTenant", ctx, userID)
	ret0, _ := ret[0].(shared.TenantID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTenant indicates an expected call of ResolveTenant.
func (mr *MockTenantResolverMockRecorder) ResolveTenant(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTenant", reflect.TypeOf((*MockTenantResolver)(nil).ResolveTenant), ctx, userID)
}
