// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	order "github.com/linkc0829/go-backend-template/internal/order"
	shared "github.com/linkc0829/go-backend-template/internal/shared"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockRepo) FindByID(ctx context.Context, id shared.OrderID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepoMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepo)(nil).FindByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockRepo) ListByUser(ctx context.Context, userID shared.UserID, p shared.Pagination) ([]*order.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, p)
	ret0, _ := ret[0].([]*order.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockRepoMockRecorder) ListByUser(ctx, userID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockRepo)(nil).ListByUser), ctx, userID, p)
}

// Save mocks base method.
func (m *MockRepo) Save(ctx context.Context, o *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(ctx, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), ctx, o)
}

// Update mocks base method.
func (m *MockRepo) Update(ctx context.Context, o *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepoMockRecorder) Update(ctx, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepo)(nil).Update), ctx, o)
}

// MockUserLookup is a mock of UserLookup interface.
type MockUserLookup struct {
	ctrl     *gomock.Controller
	recorder *MockUserLookupMockRecorder
}

// MockUserLookupMockRecorder is the mock recorder for MockUserLookup.
type MockUserLookupMockRecorder struct {
	mock *MockUserLookup
}

// NewMockUserLookup creates a new mock instance.
func NewMockUserLookup(ctrl *gomock.Controller) *MockUserLookup {
	mock := &MockUserLookup{ctrl: ctrl}
	mock.recorder = &MockUserLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLookup) EXPECT() *MockUserLookupMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockUserLookup) Exists(ctx context.Context, id shared.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserLookupMockRecorder) Exists(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserLookup)(nil).Exists), ctx, id)
}

// MockPaymentCharger is a mock of PaymentCharger interface.
type MockPaymentCharger struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentChargerMockRecorder
}

// MockPaymentChargerMockRecorder is the mock recorder for MockPaymentCharger.
type MockPaymentChargerMockRecorder struct {
	mock *MockPaymentCharger
}

// NewMockPaymentCharger creates a new mock instance.
func NewMockPaymentCharger(ctrl *gomock.Controller) *MockPaymentCharger {
	mock := &MockPaymentCharger{ctrl: ctrl}
	mock.recorder = &MockPaymentChargerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCharger) EXPECT() *MockPaymentChargerMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentCharger) Charge(ctx context.Context, userID shared.UserID, orderID shared.OrderID, amount shared.Money) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentChargerMockRecorder) Charge(ctx, userID, orderID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentCharger)(nil).Charge), ctx, userID, orderID, amount)
}
